name: BowWars
api: [3.0.0]
version: 1.1.0
main: bw\BowWars
author: RaphaTheDev
permissions:
  bw.cmd:
    description: Permission to all BowWars commands
    default: op
    children:
      bw.cmd.help:
        description: Permission for /bw help
        default: op
      bw.cmd.create:
        description: Permission for /bw create
        default: op
      bw.cmd.remove:
        description: Permission for /bw remove
        default: op
      bw.cmd.set:
        description: Permission for /bw set
        default: op
      bw.cmd.arenas:
        description: Permission for /bw arenas
        default: op
